<ul class="dropdown-menu scrollable-dropdown" aria-labelledby="dropdownMenuButton1">
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-adjust"></i>&nbsp;&nbsp;&nbsp;fa fa-adjust</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-address-book"></i>&nbsp;&nbsp;&nbsp;fa fa-address-book</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-address-book-o"></i>&nbsp;&nbsp;&nbsp;fa fa-address-book-o</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-address-card"></i>&nbsp;&nbsp;&nbsp;fa fa-address-card</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-anchor"></i>&nbsp;&nbsp;&nbsp;fa fa-anchor</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-archive"></i>&nbsp;&nbsp;&nbsp;fa fa-archive</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-area-chart"></i>&nbsp;&nbsp;&nbsp;fa fa-area-chart</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-arrows"></i>&nbsp;&nbsp;&nbsp;fa fa-arrows</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-arrows-h"></i>&nbsp;&nbsp;&nbsp;fa fa-arrows-h</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-arrows-v"></i>&nbsp;&nbsp;&nbsp;fa fa-arrows-v</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-at"></i>&nbsp;&nbsp;&nbsp;fa fa-at</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-automobile"></i>&nbsp;&nbsp;&nbsp;fa fa-automobile</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-ban"></i>&nbsp;&nbsp;&nbsp;fa fa-ban</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bank"></i>&nbsp;&nbsp;&nbsp;fa fa-bank</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bar-chart"></i>&nbsp;&nbsp;&nbsp;fa fa-bar-chart</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-barcode"></i>&nbsp;&nbsp;&nbsp;fa fa-barcode</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bath"></i>&nbsp;&nbsp;&nbsp;fa fa-bath</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bathtub"></i>&nbsp;&nbsp;&nbsp;fa fa-bathtub</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-battery-0"></i>&nbsp;&nbsp;&nbsp;fa fa-battery-0</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-battery-1"></i>&nbsp;&nbsp;&nbsp;fa fa-battery-1</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-battery-2"></i>&nbsp;&nbsp;&nbsp;fa fa-battery-2</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-battery-3"></i>&nbsp;&nbsp;&nbsp;fa fa-battery-3</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-battery-4"></i>&nbsp;&nbsp;&nbsp;fa fa-battery-4</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bell"></i>&nbsp;&nbsp;&nbsp;fa fa-bell</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bell-slash"></i>&nbsp;&nbsp;&nbsp;fa fa-bell-slash</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bicycle"></i>&nbsp;&nbsp;&nbsp;fa fa-bicycle</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-blind"></i>&nbsp;&nbsp;&nbsp;fa fa-blind</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-book"></i>&nbsp;&nbsp;&nbsp;fa fa-book</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bookmark-o"></i>&nbsp;&nbsp;&nbsp;fa fa-bookmark-o</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bug"></i>&nbsp;&nbsp;&nbsp;fa fa-bug</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-bus"></i>&nbsp;&nbsp;&nbsp;fa fa-bus</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-cab"></i>&nbsp;&nbsp;&nbsp;fa fa-cab</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-camera"></i>&nbsp;&nbsp;&nbsp;fa fa-camera</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-car"></i>&nbsp;&nbsp;&nbsp;fa fa-car</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-child"></i>&nbsp;&nbsp;&nbsp;fa fa-child</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-clone"></i>&nbsp;&nbsp;&nbsp;fa fa-clone</li>
	<li onclick="setInput(this)" style="cursor: pointer;">&nbsp;&nbsp;<i class="fa fa-close"></i>&nbsp;&nbsp;&nbsp;fa fa-close</li></ul>
